[project]
name = "langgraph-deep-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langgraph>=0.3.27",
    "ollama>=0.4.7",
]
